### ISSUE TITLE
when quotes get longer the other element goes weird

### ISSUE THREAD

**Issue by akrindev** [nyancodeid/quotes#92] opened 2021-10-05 16:21 UTC
I thought when quotes get longer the other element goes weird. it looks like we have blank block here.

![Screenshot from 2021-10-05 23-13-16](https://user-images.githubusercontent.com/33445459/136061866-8b923f77-3b84-474a-b691-f2eb54140db5.png)

what about to make their height same with each other. I mean we hide long quote's by previewing them, then make it visible when we hover on it. like how facebook does for their status profile. and yes add animation on it so the page will still look live.

**Comment by nyancodeid** [comment] 2021-10-05 16:36
Great idea, but maybe not, because when we equalize the height we will lose the dynamic height feature provided by the css grid. And I feel this feature has its own benefits in quote card with a height that is considered normal. 

I have an idea what if we put the quotes with the highest number of words at the end, so we hope that they are in the same position with the same height as well.

What do you think @akrindev 🤔

**Comment by nyancodeid** [comment] 2021-10-05 17:15
I have another solution. I merge 2 column when it quotes more than 25 word count. And it's look like this:

![image](https://user-images.githubusercontent.com/24630806/136070746-2e6061e2-baca-440f-9bc6-0553d661cbbb.png)

But, the problem is we need to place it on the right place or it gonna mess up look like this:

![image](https://user-images.githubusercontent.com/24630806/136070867-48699377-039d-459c-b9d2-f917919a7734.png)

**Comment by akrindev** [comment] 2021-10-06 00:17
Dang!! that UI is too perfect o.o

that a good idea merge 2 columns for long quotes. what about to merge column  7th? we put long quotes on every 7th loop. so it wont conflict with siblings element. what do you think @nyancodeid ?

**Comment by nyancodeid** [comment] 2021-10-06 01:02
Yes, i think it will works on 4 column display. But doesn't work on 3 column display.

**Comment by ngekoding** [comment] 2021-10-06 09:43
> Great idea, but maybe not, because when we equalize the height we will lose the dynamic height feature provided by the css grid. And I feel this feature has its own benefits in quote card with a height that is considered normal.
> 
> I have an idea, what if we put the quotes with the highest number of words at the end, so we hope that they are in the same position with the same height as well.
> 
> What do you think @akrindev 🤔

I was thinking about this also, and I agree with your idea above. We can use ordering feature base on the numbers of words. So the height different for nearest card not too big.

**Comment by nyancodeid** [comment] 2021-10-06 10:08
> > Great idea, but maybe not, because when we equalize the height we will lose the dynamic height feature provided by the css grid. And I feel this feature has its own benefits in quote card with a height that is considered normal.
> > I have an idea, what if we put the quotes with the highest number of words at the end, so we hope that they are in the same position with the same height as well.
> > What do you think @akrindev thinking
> 
> I was thinking about this also, and I agree with your idea above. We can use ordering feature base on the numbers of words. So the height different for nearest card not too big.

I agree, this what we can do for now. Rather than leaving quote cards with unequal heights (on the current website). For now we can do this first.

**Comment by ngekoding** [comment] 2021-10-06 11:17
I think unequal card height make it harder to read, because the start point for reading is different for each card in the same row, and that make an extra scroll.

**Comment by nyancodeid** [comment] 2021-10-08 02:31
It should fix with PR #119 and #126 

But something interesting happend 
![image](https://user-images.githubusercontent.com/24630806/136488894-91b12c57-adeb-46a1-96d0-b488286aa802.png)

**Comment by ngekoding** [comment] 2021-10-08 03:07
It is so funny and very interesting :D

**Comment by nyancodeid** [comment] 2021-10-08 03:25
maybe we use  `col-span-2' only, but with the condition that there must be a quote that uses `col-span-1`, if only `col-span-2' appears then we fall back to all of them into `col-span-1`. How about this?

**Comment by nyancodeid** [comment] 2021-10-09 04:34
> I have suggestions, how about we create card with same size and longer text will become dot (...), When user hover that card, they expand.

great solution, but we've covered this before. and other reasons why we can't use the ellipsis (...) solution because quotes must be displayed in full form so that the message and intent can be conveyed directly.

We should be done with this issue but there are some cases we need to handle differently.

**Comment by ngekoding** [comment] 2021-10-09 05:38
Sorry can't make a test yet.

**Comment by nyancodeid** [comment] 2021-10-09 10:36
No worry about it @ngekoding, do it if you have free time. that's how open-source should work. 😉️

**Comment by nyancodeid** [comment] 2021-10-15 02:23
I think we can skip this issue due it is rare to find. Thanks all, i gonna close this.

**Closed by nyancodeid** 2021-10-15 02:23 UTC
Labels: enhancement
